### PR TITLE
Making HAL dependency optional

### PR DESCRIPTION
**Pull request by nopper**
This simple patch just make the libhal dependency optional.

### CODE REVIEW

**Comment by obilodeau** [comment]
I was able to get firesheep to work on firefox 7 on linux Backtrack 5 R1 by merging this into master. +1 for merge

**Comment by nopper** [comment]
Hi @egbutter! Actually I did not receive any comments or reason for this pull request. I don't know what @codebutler thinks about this possible merge.

**Comment by egbutter** [comment]
well, thanks for publishing this -- it was helpful for me!

**Comment by codebutler** [comment]
Hi everyone,

The main reason I used HAL at the time was because it provided "friendly" interface names. Is it possible to get this using only udev?

**Comment by egbutter** [comment]
Sorry for the delay -- I overlooked the email.  Yes, now udev allows all the device discovery HAL allowed: https://fedoraproject.org/wiki/Features/HalRemoval.

**Comment by codebutler** [comment]
Can someone update this patch to use udev for interface names?

**Comment by egbutter** [comment]
I would love to.  I have not had much side project time lately, so do not
expect this from me any time soon.

Eric

**Comment by carbine77** [comment]
Stop sending me  your messages please.

Sent from my Windows Phone

**Comment by egbutter** [comment]
(@carbine77 unsubscribe from email notifications, then!)

**Comment by nopper** [comment]
I am closing this pull request since #192 contains the updated patch

**Pull request closed without merging**
